name: apres_archiving
channels:
  - conda-forge
dependencies:
  - python==3.13.5
  - numpy==2.3.1
  - xarray==2025.6.1
  - ipykernel==6.29.5
  - jupyterlab==4.4.4
  - geopandas==1.1.1
  - rioxarray==0.19.0
  - openpyxl==3.1.5
  - pip:
      - xapres==0.5.4